logging:
  level: INFO
  loggers:
    net.leanix: DEBUG
server:
  applicationConnectors:
    - type: http
      port: 8082
      outputBufferSize: 32KiB
      idleTimeout: 30 seconds
      minBufferPoolSize: 64 bytes
      bufferPoolIncrement: 1KiB
      maxBufferPoolSize: 64KiB
      acceptorThreads: 1
      selectorThreads: 2
      acceptQueueSize: 1024
      reuseAddress: true
      soLingerTime: 600s
  adminConnectors:
    - type: http
      port: 8083
#database:
#  port: 27018
#  host: localhost
#  db_name: todos-db
#  collection: todos
